// src/pages/PracticeAgreementPrint.jsx
//
// Print-friendly view of the practice agreement. Used for:
//   - "Download / Print PDF" button on the therapist editor
//     (browser print dialog -> Save as PDF)
//   - Older clients who want to sign on paper (therapist prints,
//     client signs with pen, therapist scans/uploads later)
//
// No browser chrome, no app nav. Just the document with signature
// lines at the bottom. Auto-triggers window.print() if ?print=1.

import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { AgreementRenderer } from '../components/PracticeAgreement';
import { renderAgreementForClient, DEFAULT_PRACTICE_AGREEMENT } from '../lib/practiceAgreement';

export default function PracticeAgreementPrint() {
  const { user } = useAuth();
  const [therapist, setTherapist] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      if (!user?.id) { setLoading(false); return; }
      const { data } = await supabase
        .from('therapists')
        .select('*')
        .eq('id', user.id)
        .single();
      setTherapist(data || null);
      setLoading(false);
    })();
  }, [user?.id]);

  // Auto-trigger print after content renders, if ?print=1
  useEffect(() => {
    if (loading || !therapist) return;
    const params = new URLSearchParams(window.location.search);
    if (params.get('print') === '1') {
      // Defer to next frame so the agreement is fully rendered first
      setTimeout(() => window.print(), 400);
    }
  }, [loading, therapist]);

  if (loading) return <div style={{ padding: 40 }}>Loading...</div>;
  if (!therapist) return <div style={{ padding: 40 }}>Therapist record not found. Please sign in.</div>;

  const text = therapist.practice_agreement_text || DEFAULT_PRACTICE_AGREEMENT;
  const rendered = renderAgreementForClient(text, therapist);
  const business = therapist.business_name || therapist.full_name || '';

  return (
    <>
      <style>{`
        @media print {
          @page { size: letter; margin: 0.6in; }
          body { background: #fff !important; }
          .no-print { display: none !important; }
        }
        body { background: #fff; }
      `}</style>

      <div style={{
        maxWidth: 720,
        margin: '0 auto',
        padding: '32px 0 60px',
        fontFamily: 'Georgia, serif',
        color: '#1F2937',
        fontSize: 13,
        lineHeight: 1.65,
      }}>
        {/* Branded header + body. AgreementRenderer renders the same
            chrome the therapist sees in their editor: forest header
            with business name, ABMP/AMTA attribution, then sections. */}
        <AgreementRenderer text={rendered} businessName={business} />

        {/* Signature block */}
        <div style={{
          marginTop: 24,
          background: '#FEF3C7',
          border: '2px solid #FCD34D',
          borderRadius: 12,
          padding: '20px 24px',
        }}>
          <div style={{ fontSize: 11, fontWeight: 700, fontFamily: 'Georgia, serif', color: '#92400E', marginBottom: 18, letterSpacing: '0.14em', textTransform: 'uppercase' }}>
            Signature
          </div>

          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 11, color: '#92400E', marginBottom: 4 }}>Client name (please print)</div>
            <div style={{ borderBottom: '1.5px solid #1F2937', height: 24 }} />
          </div>

          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 11, color: '#92400E', marginBottom: 4 }}>Signature</div>
            <div style={{ borderBottom: '1.5px solid #1F2937', height: 34 }} />
          </div>

          <div style={{ display: 'flex', gap: 20 }}>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 11, color: '#92400E', marginBottom: 4 }}>Date</div>
              <div style={{ borderBottom: '1.5px solid #1F2937', height: 24 }} />
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          marginTop: 24,
          textAlign: 'center',
          fontSize: 10,
          color: '#9CA3AF',
        }}>
          Generated by MyBodyMap · Based on ABMP and AMTA professional standards
        </div>

        {/* Screen-only print button */}
        <div className="no-print" style={{
          position: 'fixed',
          bottom: 20,
          right: 20,
          display: 'flex',
          gap: 8,
        }}>
          <button
            onClick={() => window.print()}
            style={{
              background: '#2A5741',
              color: '#fff',
              border: 'none',
              borderRadius: 10,
              padding: '11px 22px',
              fontSize: 13,
              fontWeight: 700,
              cursor: 'pointer',
              boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            }}
          >
            Print / Save PDF
          </button>
          <button
            onClick={() => window.close()}
            style={{
              background: '#fff',
              border: '1px solid #E5E7EB',
              borderRadius: 10,
              padding: '11px 16px',
              fontSize: 13,
              fontWeight: 600,
              color: '#6B7280',
              cursor: 'pointer',
            }}
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
