import React from 'react';
const C = { forest: '#2A5741', darkGray: '#1F2937', gray: '#6B7280', lightGray: '#F9FAFB', border: '#E5E7EB' };
export default function Privacy() {
  const items = [
    { title: '1. Who We Are', body: 'BodyMap LLC, a Wyoming limited liability company doing business as MyBodyMap, operates mybodymap.app and the MyBodyMap platform. Our registered office is 30 N Gould St, Ste N, Sheridan, WY 82801. Contact us at support@mybodymap.app.' },
    { title: '2. What Data We Collect', body: 'Therapist data: name, business name, email, phone, license number. Payment data processed by Stripe - we never store card details.\n\nClient intake data: name, phone, body map selections (areas of focus or discomfort tapped on a body diagram), session preferences, massage goals, pressure preferences, and health information voluntarily provided through intake forms. This includes pain areas, medical history, medications, allergies, and any other intake information the therapist chooses to collect through MyBodyMap.\n\nSession data: therapist notes, completion status, feedback, session dates, and longitudinal patterns derived from session history (such as repeated focus areas across sessions).\n\nUsage data: browser type, device type, pages visited - collected anonymously.' },
    { title: '3. How We Use Your Data', body: 'To operate the platform, enable session management, send intake links, process payments, improve features, and provide longitudinal pattern insights to the therapist about their own clients (such as repeated focus areas across sessions). These pattern insights are only visible to the therapist whose practice the data belongs to and are derived from data the client provided through that therapist\'s intake forms.\n\nWe may use anonymized, de-identified, aggregated data to improve the Service for all therapists. "De-identified" means all personally identifiable information (name, phone, email, therapist identity, client identity) has been permanently removed.\n\nWe do not use your data for advertising. We do not sell your data. Ever.' },
    { title: '4. How Your Data Is Protected', body: 'MyBodyMap runs on Supabase infrastructure with: AES-256 encryption at rest, TLS 1.3 encryption in transit, and Row Level Security ensuring each therapist can only access their own data.\n\nOur infrastructure providers (including Supabase, Vercel, Stripe, Resend, and Twilio) maintain SOC 2 Type II and similar industry-standard security certifications. MyBodyMap itself has not undergone a SOC 2 audit at this time.\n\nWe maintain commercially reasonable backup procedures and an audit log of database changes. No security system is infallible. You may request a copy of your data at any time by emailing support@mybodymap.app, and we will provide it within fourteen (14) business days.' },
    { title: '5. Data Sharing', body: 'MyBodyMap is the SMS program operator. No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. Information sharing with subcontractors in support services, such as customer service, is permitted. All other use case categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.\n\nMore broadly: we do not sell, rent, or share your phone number, email address, or any personal data with third parties for marketing purposes. Phone numbers collected for SMS messaging are used solely to deliver appointment reminders, confirmations, and follow-ups via the MyBodyMap platform. We share operational data only with: Supabase (hosting), Stripe (payments), Resend (email delivery), and Twilio (SMS delivery). All providers are contractually bound to protect your data and process it only on our behalf as service subcontractors.' },
    { title: '5a. SMS Messaging', body: 'When you provide your phone number to your massage therapist through their MyBodyMap booking page and explicitly check the SMS consent checkbox, you consent to receive transactional SMS messages from your therapist via the MyBodyMap platform. These include: booking confirmations, appointment reminders (typically 24-48 hours before your appointment), intake form links, post-session follow-ups, and gentle re-engagement messages if you have not booked recently. SMS consent is voluntary; you can complete a booking without consenting to SMS, in which case no text messages will be sent to you.\n\nMessage frequency: SMS volume varies based on your booking activity and your therapist\'s notification preferences. Typical frequency is 2 to 5 messages per booked appointment.\n\nMessage and data rates may apply. Standard carrier rates from your mobile provider apply to all SMS sent and received.\n\nOpt-out: You may unsubscribe at any time by replying STOP, STOPALL, UNSUBSCRIBE, CANCEL, END, or QUIT to any message. Replying HELP returns contact information for support.\n\nNo mobile information will be shared with third parties or affiliates for marketing or promotional purposes. SMS opt-in data and consent records are never sold, rented, or shared with any third party for any reason.' },
    { title: '5b. Google Calendar Integration', body: 'Connecting your Google Calendar is optional. If you choose to connect it, you sign in with your own Google account and grant MyBodyMap permission to view and manage your calendar events (the calendar.events permission). The integration works in both directions.\n\nMyBodyMap to Google: for each session booked through MyBodyMap, we create an event on your own Google Calendar, and we update or delete that event when the session is rescheduled or cancelled.\n\nGoogle to MyBodyMap: so that your existing commitments are not double-booked, we periodically read your upcoming Google Calendar events (about 60 days ahead) and store each event\'s title, start time, and end time. We use this only to mark those times as unavailable on your booking page. We skip the session events MyBodyMap itself created, and we read your calendar\'s time zone to set your business time zone.\n\nWe do not access your clients\' calendars, and we use your Google Calendar data solely to provide these scheduling features within MyBodyMap.\n\nLimited use: MyBodyMap\'s use of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements. We do not use Google Calendar data for advertising, we do not sell it, we do not transfer it to third parties, and we do not use it to train AI or machine learning models. No MyBodyMap staff member reads your Google Calendar data; event details are shown back only to you, the therapist whose calendar it is.\n\nDisconnecting: you can disconnect Google Calendar at any time from your MyBodyMap settings, or by removing MyBodyMap\'s access in your Google Account at myaccount.google.com/permissions. Disconnecting stops all future syncing.' },
    { title: '6. Client Data', body: 'Therapists are responsible for informing clients that intake data is stored digitally and obtaining all necessary consents under applicable law. Therapists are the data controllers for their clients\' information; MyBodyMap is a data processor acting on the therapist\'s behalf.\n\nClients may request access to or deletion of their data by contacting their therapist directly, or by emailing support@mybodymap.app. We will process such requests within 30 days, in coordination with the therapist whose practice the data belongs to.\n\nIf you are a HIPAA Covered Entity or Business Associate, you may not use the Service to store or transmit Protected Health Information (PHI). MyBodyMap is not a HIPAA-covered platform and does not sign Business Associate Agreements (BAAs). If your practice is HIPAA-covered, consult with your legal counsel before using the Service.' },
    { title: '7. Data Retention', body: 'Data is retained while your account is active. On closure, retained 30 days then permanently deleted.' },
    { title: '8. Your Rights (CCPA and similar laws)', body: 'California residents and residents of other states with comparable privacy laws have the right to know what data we collect about them, request deletion, and opt out of any sale of personal information (we do not sell data). To exercise these rights, contact support@mybodymap.app.\n\nWe will respond to verifiable requests within 30 days. We may need to verify your identity before processing your request.' },
    { title: '9. Cookies', body: 'We use only essential cookies for authentication. No tracking cookies, no advertising cookies.' },
    { title: '10. Changes', body: 'We may update this Privacy Policy from time to time. When we make material changes, we will update the "Last updated" date at the top and provide at least thirty (30) days\' notice by email or platform notice before the changes take effect. Your continued use of the Service after the effective date constitutes acceptance of the updated Privacy Policy.' },
    { title: '11. Contact', body: 'BodyMap LLC, doing business as MyBodyMap\n30 N Gould St, Ste N\nSheridan, WY 82801\nsupport@mybodymap.app\nmybodymap.app' },
  ];
  return (
    <div style={{ background: C.lightGray, minHeight: '100vh', padding: '60px 24px' }}>
      <div style={{ maxWidth: '780px', margin: '0 auto 24px auto' }}>
        <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
          <span style={{ fontSize: '22px' }}>🌿</span>
          <span style={{ fontSize: '18px', fontWeight: '800', color: '#2A5741', letterSpacing: '-0.3px' }}>MyBodyMap</span>
        </a>
      </div>
      <div style={{ maxWidth: '780px', margin: '0 auto', background: 'white', borderRadius: '16px', padding: '56px 64px', boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}>
        <div style={{ marginBottom: '40px' }}>
          <div style={{ fontSize: '13px', color: C.gray, marginBottom: '8px' }}>Effective Date: May 25, 2026 · Last updated: June 12, 2026</div>
          <h1 style={{ fontSize: '36px', fontWeight: '700', color: C.darkGray, margin: '0 0 12px 0' }}>Privacy Policy</h1>
          <p style={{ fontSize: '16px', color: C.gray, lineHeight: '1.6', margin: 0 }}>BodyMap LLC is committed to protecting the privacy of therapists and their clients.</p>
        </div>
        {items.map((s) => (
          <div key={s.title} style={{ marginBottom: '36px', paddingBottom: '36px', borderBottom: '1px solid ' + C.border }}>
            <h2 style={{ fontSize: '18px', fontWeight: '700', color: C.darkGray, margin: '0 0 12px 0' }}>{s.title}</h2>
            <p style={{ fontSize: '15px', color: C.gray, lineHeight: '1.7', margin: 0, whiteSpace: 'pre-line' }}>{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
