import React from 'react';
const C = { forest: '#2A5741', darkGray: '#1F2937', gray: '#6B7280', lightGray: '#F9FAFB', border: '#E5E7EB' };
export default function Terms() {
  const items = [
    { title: '1. What MyBodyMap Is', body: 'MyBodyMap is a client communication and intake management tool for licensed massage therapists. It is NOT a medical platform, EHR, or HIPAA-covered entity. Therapists are solely responsible for all clinical decisions.' },
    { title: '2. Eligibility', body: 'You must be at least 18 years old to use MyBodyMap. By using this platform you represent that you are a licensed wellness professional or a client of one.' },
    { title: '3. Your Account', body: 'You are responsible for maintaining confidentiality of your login credentials. Notify us at support@mybodymap.app if you suspect unauthorized access.' },
    { title: '4. Acceptable Use', body: 'You agree not to use MyBodyMap to collect data for unauthorized purposes, access another user\'s data, reverse engineer the platform, or use it for any unlawful purpose.' },
    { title: '5. Subscription and Payments', body: 'Paid plans are billed monthly or annually through Stripe. Cancel anytime - access continues until end of your current billing period. Monthly subscriptions are non-refundable for partial periods. If you cancel an annual subscription, you may request a pro-rata refund for the unused portion of the term by emailing support@mybodymap.app within 14 days of cancellation. All other fees are non-refundable except as expressly required by law or as we may choose to refund in our discretion.' },
    { title: '6. SMS Communications', body: 'When you provide your phone number on a MyBodyMap booking page or therapist signup form and explicitly check the SMS consent checkbox, you agree to receive SMS messages from your therapist via the MyBodyMap platform. SMS consent is given directly to MyBodyMap and is voluntary; it is not bundled with, conditional on, or required by any third-party agreement or by completion of the booking itself. You may complete a booking without consenting to SMS, in which case no text messages will be sent to you. These messages may include appointment reminders, booking confirmations, post-session follow-ups, and re-engagement messages. Therapist accounts may also receive product updates, onboarding tips, and account messages from MyBodyMap directly.\n\nMessage frequency varies based on your booking activity (typically 2-6 messages per month per therapist relationship). Message and data rates may apply, charged by your mobile carrier. We do not charge for SMS.\n\nYou can opt out at any time by replying STOP, STOPALL, UNSUBSCRIBE, CANCEL, END, or QUIT to any message. After opting out, you will receive one final confirmation message and no further texts. To re-subscribe, reply START. For help, reply HELP or email support@mybodymap.app.\n\nNo mobile information will be shared with third parties or affiliates for marketing or promotional purposes. We will never sell your phone number, share it with third parties for marketing, or use it for purposes outside the booking and communication features of the platform. SMS opt-in data and consent records are not shared across therapist accounts, not used to train AI, and not shared with any third party for any reason.' },
    { title: '7. Client Data Responsibility', body: 'As a therapist, you are the data controller for your clients information. You are responsible for obtaining client consent to store their intake data on MyBodyMap.' },
    { title: '8. Not Medical Software', body: 'MyBodyMap is a communication tool, not medical software. It is not designed to store protected health information (PHI) under HIPAA. BodyMap LLC does not sign Business Associate Agreements (BAAs).' },
    { title: '9. Limitation of Liability', body: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW: (A) IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOST PROFITS, LOST REVENUE, LOST BUSINESS OPPORTUNITY, LOST GOODWILL, LOST DATA, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE, REGARDLESS OF WHETHER SUCH DAMAGES WERE FORESEEABLE OR WHETHER A PARTY HAS BEEN ADVISED OF THEIR POSSIBILITY, AND REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, STRICT LIABILITY, STATUTORY, OR OTHERWISE).\n\n(B) EXCEPT FOR YOUR PAYMENT OBLIGATIONS AND YOUR INDEMNIFICATION OBLIGATIONS UNDER SECTION 11, OUR AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS WILL NOT EXCEED THE TOTAL FEES PAID BY YOU TO US IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM. THIS LIMITATION APPLIES IN AGGREGATE TO ALL CLAIMS AND CAUSES OF ACTION.\n\n(C) THE FOREGOING LIMITATIONS APPLY EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.\n\n(D) NOTHING IN THESE TERMS LIMITS LIABILITY FOR FRAUD, WILLFUL MISCONDUCT, OR ANY OTHER LIABILITY THAT CANNOT BE LIMITED UNDER APPLICABLE LAW.\n\nYOU ACKNOWLEDGE THAT THE FEES WE CHARGE REFLECT THE ALLOCATION OF RISK SET FORTH IN THESE TERMS, AND THAT WE WOULD NOT PROVIDE THE SERVICE WITHOUT THESE LIMITATIONS.' },
    { title: '10. Disclaimer of Warranties', body: 'EXCEPT AS EXPRESSLY SET FORTH IN THESE TERMS, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. WE SPECIFICALLY DISCLAIM ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.\n\nWE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, FREE OF VIRUSES OR HARMFUL COMPONENTS, OR THAT ALL DEFECTS WILL BE CORRECTED. WE DO NOT WARRANT ANY SPECIFIC RESULTS FROM USING THE SERVICE, INCLUDING ANY IMPROVEMENT IN YOUR BUSINESS, CLIENT RETENTION, OR FINANCIAL OUTCOMES.\n\nTHE SERVICE IS A SOFTWARE TOOL. WE DO NOT PROVIDE PROFESSIONAL, MEDICAL, OR HEALTHCARE ADVICE. ANY INFORMATION GENERATED OR DISPLAYED BY THE SERVICE, INCLUDING ANY PATTERN INTELLIGENCE OR INSIGHTS DERIVED FROM SESSION DATA, IS FOR INFORMATIONAL PURPOSES ONLY AND DOES NOT CONSTITUTE PROFESSIONAL ADVICE OR A SUBSTITUTE FOR YOUR PROFESSIONAL JUDGMENT.' },
    { title: '11. Indemnification', body: 'You agree to defend, indemnify, and hold harmless BodyMap LLC, its members, managers, officers, employees, agents, and affiliates (collectively, the "Indemnified Parties") from and against any claims, damages, losses, liabilities, judgments, settlements, costs, and expenses (including reasonable attorneys\' fees) arising out of or related to: (a) your use of the Service in violation of these Terms or applicable law; (b) any Customer Content you submit to the Service, including any allegation that such content infringes a third party\'s rights or violates law; (c) your interactions with your clients, including any claim relating to the professional services you provided, your professional negligence, the adequacy of the care you provided, or any injury alleged to have resulted from your services; (d) your failure to obtain required consents, licenses, or authorizations; and (e) any breach by you of any representation or warranty in these Terms.\n\nWe will give you reasonable notice of any claim subject to indemnification and reasonable cooperation in the defense. You may not settle any claim without our prior written consent if the settlement requires us to take any action, refrain from any action, or admit any liability.' },
    { title: '12. Customer\'s Responsibility for Data and Backups', body: 'You are responsible for backing up your own data and maintaining copies of all information critical to your business. We provide commercially reasonable backup and recovery procedures for our operational needs, but no backup system is infallible. You may request a copy of your data at any time by emailing support@mybodymap.app, and we will provide it within fourteen (14) business days.\n\nYour sole remedy for any data loss is our commercially reasonable efforts to restore from our backups, subject to the limitations of liability in Section 9.' },
    { title: '13. Service Availability', body: 'We will use commercially reasonable efforts to make the Service available. We do not guarantee any specific uptime percentage. The Service may be unavailable due to scheduled maintenance, unscheduled maintenance, force majeure events, or third-party service interruptions.\n\nYour sole remedy for prolonged Service unavailability is to terminate this Agreement and receive a pro-rata refund of prepaid, unused fees for the affected period.\n\nWe may modify, suspend, or discontinue any feature of the Service at any time. We will use commercially reasonable efforts to provide advance notice of material changes that adversely affect your use of the Service.' },
    { title: '14. Required Notice and Cure Period', body: 'Before initiating any claim, demand for arbitration, or legal proceeding against us, you must provide us with written notice describing the alleged breach in reasonable detail. The notice must be sent to support@mybodymap.app. We will have thirty (30) days from receipt of such notice to investigate and cure the alleged breach. No claim or proceeding may be commenced until the cure period has expired without cure.\n\nThis Section does not apply to claims for injunctive relief to prevent imminent irreparable harm.' },
        { title: '15. Intellectual Property', body: 'All platform content, design, and software are owned by BodyMap LLC. You may not copy, modify, or distribute any part of the platform without written permission.' },
    { title: '16. Termination', body: 'You may close your account at any time by emailing support@mybodymap.app. Data is retained for 30 days then permanently deleted.' },
    { title: '17. Governing Law', body: 'These terms are governed by the laws of the State of Wyoming. Disputes shall be resolved in the courts of Sheridan County, Wyoming.' },
    { title: '18. Arbitration and Dispute Resolution', body: 'PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS.\n\nBinding Arbitration: Any dispute, claim, or controversy arising out of or relating to these Terms or the Service, except as expressly excluded below, will be resolved through binding arbitration administered by the American Arbitration Association (AAA) in accordance with its Commercial Arbitration Rules. The arbitration will be conducted in Sheridan County, Wyoming, by a single arbitrator. The arbitrator\'s decision will be final and binding. Judgment on the award may be entered in any court of competent jurisdiction.\n\nClass Action Waiver: YOU AND BODYMAP LLC EACH WAIVE THE RIGHT TO A JURY TRIAL AND THE RIGHT TO BRING OR PARTICIPATE IN ANY CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION. ANY ARBITRATION WILL PROCEED ON AN INDIVIDUAL BASIS ONLY.\n\nSmall Claims Carveout: Notwithstanding the above, either party may bring an individual action in small claims court for claims that qualify, so long as the action remains in that court and is not removed or appealed to a court of general jurisdiction.\n\nInjunctive Relief: Either party may seek injunctive or other equitable relief in a court of competent jurisdiction in Sheridan County, Wyoming, for matters relating to intellectual property infringement, unauthorized access to the Service, or breach of confidentiality.\n\nOpt-Out: You may opt out of the arbitration agreement and class action waiver by sending written notice to support@mybodymap.app within thirty (30) days of first accepting these Terms. Your opt-out notice must include your full name, the email address associated with your account, and a clear statement that you opt out of arbitration.' },
    { title: '19. Changes', body: 'We may update these Terms from time to time. When we make material changes, we will: update the "Last Updated" date at the top of these Terms; provide at least thirty (30) days\' notice through the Service or by email before the changes take effect; and if you do not agree to the changes, you may terminate your account before the effective date.\n\nYour continued use of the Service after the effective date constitutes acceptance of the updated Terms.' },
    { title: '20. Contact', body: 'BodyMap LLC, doing business as MyBodyMap\n30 N Gould St, Ste N\nSheridan, WY 82801\nsupport@mybodymap.app\nmybodymap.app' },
  ];
  return (
    <div style={{ background: C.lightGray, minHeight: '100vh', padding: '60px 24px' }}>
      <div style={{ maxWidth: '780px', margin: '0 auto 24px auto' }}>
        <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', textDecoration: 'none' }}>
          <span style={{ fontSize: '22px' }}>🌿</span>
          <span style={{ fontSize: '18px', fontWeight: '800', color: '#2A5741', letterSpacing: '-0.3px' }}>MyBodyMap</span>
        </a>
      </div>
      <div style={{ maxWidth: '780px', margin: '0 auto', background: 'white', borderRadius: '16px', padding: '56px 64px', boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}>
        <div style={{ marginBottom: '40px' }}>
          <div style={{ fontSize: '13px', color: C.gray, marginBottom: '8px' }}>Effective Date: May 25, 2026 · Last updated: May 25, 2026</div>
          <h1 style={{ fontSize: '36px', fontWeight: '700', color: C.darkGray, margin: '0 0 12px 0' }}>Terms of Service</h1>
          <p style={{ fontSize: '16px', color: C.gray, lineHeight: '1.6', margin: 0 }}>These Terms of Service govern your use of MyBodyMap, operated by BodyMap LLC, a Wyoming limited liability company doing business as MyBodyMap. By using the Service, you agree to be bound by these Terms.</p>
        </div>
        {items.map((s) => (
          <div key={s.title} style={{ marginBottom: '36px', paddingBottom: '36px', borderBottom: '1px solid ' + C.border }}>
            <h2 style={{ fontSize: '18px', fontWeight: '700', color: C.darkGray, margin: '0 0 12px 0' }}>{s.title}</h2>
            <p style={{ fontSize: '15px', color: C.gray, lineHeight: '1.7', margin: 0, whiteSpace: 'pre-line' }}>{s.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
